Creating seperate homepages/ teller authentication to teller's index
majulahsingapuri/capstone3 pull request #2
Opened 2023-10-20 08:57 UTC by mushroomyyy

2023-10-20 08:58 UTC, Jus323 approved these changes

2023-10-24 01:44 UTC, helmyrsln approved these changes

2023-10-24 01:59 UTC, majulahsingapuri requested changes
Is the index file still there? you might have to remove the default one then

2023-10-24 01:59 UTC, majulahsingapuri commented on capstone_db.session.sql
Keep these values commented

2023-10-24 01:59 UTC, majulahsingapuri commented on src/main/java/com/example/capstone3/MyController.java
> +        System.out.println("has teller role is: " + hasTellerRole);
remove print statements

2023-10-24 02:34 UTC, mushroomyyy reviewed
Noted and made the necessary changes

2023-10-24 02:40 UTC, majulahsingapuri approved these changes

2023-10-24 03:15 UTC, merged